language: python
python:
  - "2.7"

before_install:
  - pip install codecov

install:
  - pip install .
  - pip install -r ./requirements.txt
  - pip install flake8

before_script: flake8 ./etao/

script: nose2

after_success:
  - codecov
